"""
Real-world DSCR lender profiles.

Based on published guidelines from actual DSCR lenders (Visio, Kiavi,
Deephaven, Lima One, CoreVest, etc.) abstracted into behavioral profiles.
"""
from backend.shared_models.lender import LenderProfile, LenderType

LENDER_REGISTRY: list[LenderProfile] = [
    LenderProfile(
        lender_id="conservative_bank_a",
        lender_name="Regional Conservative Bank A",
        lender_type=LenderType.CONSERVATIVE_BANK,
        dscr_min=1.35,
        dscr_stress_min=1.20,
        ltv_max=0.70,
        loan_min=75_000,
        loan_max=1_500_000,
        property_condition_min_score=0.65,
        zip_risk_sensitivity=0.8,
        property_age_sensitivity=0.7,
        loan_size_sensitivity=0.3,
        base_rate=0.072,
        rate_spread_bps=50,
    ),
    LenderProfile(
        lender_id="dscr_specialist_b",
        lender_name="DSCR Specialist Lender B",
        lender_type=LenderType.DSCR_SPECIALIST,
        dscr_min=1.20,
        dscr_stress_min=1.05,
        ltv_max=0.80,
        loan_min=50_000,
        loan_max=3_000_000,
        property_condition_min_score=0.45,
        zip_risk_sensitivity=0.5,
        property_age_sensitivity=0.4,
        loan_size_sensitivity=0.4,
        base_rate=0.079,
        rate_spread_bps=75,
    ),
    LenderProfile(
        lender_id="aggressive_portfolio_c",
        lender_name="Aggressive Portfolio Lender C",
        lender_type=LenderType.AGGRESSIVE_PORTFOLIO,
        dscr_min=1.10,
        dscr_stress_min=0.95,
        ltv_max=0.80,
        loan_min=40_000,
        loan_max=5_000_000,
        property_condition_min_score=0.30,
        zip_risk_sensitivity=0.3,
        property_age_sensitivity=0.3,
        loan_size_sensitivity=0.5,
        base_rate=0.089,
        rate_spread_bps=100,
    ),
    LenderProfile(
        lender_id="dscr_specialist_d",
        lender_name="DSCR Specialist Lender D (Visio-type)",
        lender_type=LenderType.DSCR_SPECIALIST,
        dscr_min=1.15,
        dscr_stress_min=1.00,
        ltv_max=0.75,
        loan_min=75_000,
        loan_max=2_000_000,
        property_condition_min_score=0.50,
        zip_risk_sensitivity=0.6,
        property_age_sensitivity=0.5,
        loan_size_sensitivity=0.35,
        base_rate=0.081,
        rate_spread_bps=80,
    ),
    LenderProfile(
        lender_id="private_bridge_e",
        lender_name="Private Bridge Lender E",
        lender_type=LenderType.PRIVATE_BRIDGE,
        dscr_min=1.0,
        dscr_stress_min=0.90,
        ltv_max=0.75,
        loan_min=100_000,
        loan_max=10_000_000,
        property_condition_min_score=0.20,
        zip_risk_sensitivity=0.2,
        property_age_sensitivity=0.2,
        loan_size_sensitivity=0.6,
        base_rate=0.110,
        rate_spread_bps=150,
    ),
]
